# Generated by Django 5.2.6 on 2025-09-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
