# Generated by Django 5.2.6 on 2025-10-20 13:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_catalog_pro_sku_2c4c34_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='file'),
        ),
    ]
