# Generated by Django 5.2.6 on 2025-10-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_grand_total_order_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
